accounts/urls.py
from django.urls import re_path
from django.urls import path

from . import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'student/register/$', views.UserFormView.as_view(), name='student_register'),
    re_path(r'staff/register/$', views.StaffFormView.as_view(), name='staff_register'),
    re_path(r'login/$', views.user_login, name='login'),
    re_path(r'logout/$', views.user_logout, name='logout'),
    re_path(r'getNames/', views.getNames),
    path('activate_users/', views.Activate_Users, name='Activate_Users'),
    path('activate/<int:uid>', views.Activate, name='Activate'),
    path('deactivate/<int:uid>', views.Deactivate, name='Deactivate'),
]

content/urls.py
from django.urls import re_path
from django.conf.urls.static import static
from django.urls import include, path
from . import  views
from office_file_tracking_system import  settings

app_name='content'

urlpatterns = [
                re_path(r'^scholarships/$', views.Show_Scholarships, name=''),
                re_path(r'^scholarships/(?P<s_id>\w+)', views.Scholarship_Detail, name='Scholarship_Detail'),
                path('track_application/', views.Track_Application, name='Track_Application'),
                re_path('apply/', views.Apply, name='Apply'),
                path('add_scholarship', views.Add_Scholarship, name='Add_Scholarship'),
                path('pending_approvals/', views.Show_Pending_Approvals, name='Show_Pending_Approvals'),
                path('track_student_applications/', views.Track_Student_Applications, name='Track_Student_Applications'),
                path('approve/', views.Approve, name='Approve'),
                path('reject/', views.Reject, name='Reject'),
                path('about/', views.About, name='About'),
                path('profile/', views.Profile, name='Profile'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

office_file_tracking_system/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf.urls.static import static
from office_file_tracking_system import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include(('accounts.urls', 'accounts'), namespace='accounts')),
    re_path(r'content/', include(('content.urls', 'content'), namespace='content')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.core.validators import RegexValidator
from django.urls import reverse
from django.contrib.auth.password_validation import validate_password
from django.template.defaultfilters import slugify
from django.utils.text import slugify

class Department(models.Model):
    name = models.CharField(max_length=255, default='')
    slug = models.SlugField(max_length=30, unique=True, editable=False)
    abbreviation = models.CharField(max_length=10, default='')

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = slugify(self.name)
            while True:
                try:
                    department = Department.objects.get(slug=slug)
                    if department == self:
                        self.slug = slug
                        break
                    else:
                        slug = slug + '_'
                except:
                    self.slug = slug
                    break
        super(Department, self).save()

    def __str__(self):
        return self.name


class CustomUserManager(BaseUserManager):
    def create_user(self, username, password=None, email=None):
        if not username:
            raise ValueError('Users must have a username')
        user = self.model(
            username=username + '',
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password):
        user = self.create_user(
            username=username,
            password=password,
        )
        user.is_admin = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser, PermissionsMixin):
    GENDERS = (('M', 'Male'), ('F', 'Female'))
    ROLE_CHOICES = (
        ('Teacher', 'Teacher'),
        ('Faculty Advisor', 'Faculty Advisor'),
        ('Dean', 'Dean'),
        ('Head of department', 'Head of department'),
        ('Director', 'Director'),
        ('Admin', 'Admin'),
    )
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    mobile = models.CharField(max_length=10,
                              validators=[RegexValidator(regex=r'[0-9]{10}', message='Invalid Mobile Number')],
                              blank=True)
    role = models.CharField(max_length=50, choices=ROLE_CHOICES, default='S')
    gender = models.CharField(max_length=1, choices=GENDERS, default='M')

    registration_number = models.CharField('Registration number', max_length=7, unique=True,
                                           validators=[RegexValidator(regex=r'[a-zA-Z]{2}[0-9]{5}',
                                            message='Invalid Registration Number')], blank=True, null=True)

    department = models.ForeignKey('Department', verbose_name="Department", on_delete=models.CASCADE, blank=True, null=True)

    admin = models.CharField(max_length=1, default='N')
    password = models.CharField('password', max_length=128, validators=[validate_password])
    is_student = models.BooleanField(default=True, verbose_name='Student')
    is_active = models.BooleanField(default=True, verbose_name='Active',
                                    help_text='Designates whether this user should be treated as active. '
                                              'Unselect this instead of deleting accounts.')
    is_admin = models.BooleanField(default=False, verbose_name='Staff status',
                                   help_text='Designates whether the user can log into this admin site.')
    image = models.ImageField(default='download.jpg', upload_to='profile/')
    # notifications = models.IntegerField(default=0)
    # noti_messages = models.CharField(max_length=500, blank=True)
    USERNAME_FIELD = 'username'
    EMAIL_FIELD = 'email'

    objects = CustomUserManager()

    def __str__(self):
        return self.username

    @property
    def is_staff(self):
        return self.is_admin

    def get_absolute_url(self):
        return reverse('accounts:index')

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect,HttpResponse
from django.contrib.auth import authenticate, login
from django.views import generic
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils.http import url_has_allowed_host_and_scheme
from django.contrib import messages
from content.decorators import login_required_message
from .models import *
from .admin import UserCreationForm, StaffCreationForm
import json

def index(request):
    response = {}
    print(request.user, " logged in : RENDER HOME ")
    user = CustomUser.objects.filter(id=request.user.id)
    print("User : ",user)
    if not user or (user and user[0].is_student):
        return render(request, 'student_home.html', response)
    else:
        return render(request, 'staff_home.html', response)

class UserFormView(generic.View):
    form_class = UserCreationForm
    template_name = 'accounts/student_register.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)

        if form.is_valid():
            user = form.save(commit=False)
            print(user)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user.set_password(password)
            user.save()
            return redirect('/')

        return render(request, self.template_name, {'form': form})

class StaffFormView(generic.View):
    form_class = StaffCreationForm
    template_name = 'accounts/staff_register.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)

        if form.is_valid():
            user = form.save(commit=False)
            print(user)
            user.is_student = False
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user.set_password(password)
            user.save()
            return redirect('/')

        return render(request, self.template_name, {'form': form})

@csrf_exempt
def user_logout(request):
    logout(request)
    messages.success(request, "You have been logged out.")
    return HttpResponseRedirect('/login/')

@csrf_exempt
def user_login(request):
    response = {}
    if request.user.is_authenticated:
        logout(request)
    else:
        response = {}
    if request.method == 'POST':
        next_post = request.POST.get('next')
        redirect_path = next_post
        username = request.POST['username']
        try:
            username = CustomUser.objects.get(email=username).username
        except CustomUser.DoesNotExist:
            username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                messages.success(request, 'You have been successfully logged in.')
                if url_has_allowed_host_and_scheme(redirect_path, request.get_host()):
                    return redirect(redirect_path)
                else:
                    return redirect('accounts:index')
            else:
                messages.warning(request, 'User is not active yet')
                response['message'] = 'User is not active yet'
        else:
            messages.warning(request, 'User is invalid')
            response['message'] = 'User is invalid'

    return render(request, 'accounts/login.html', response)

@csrf_exempt
def getNames(request):
    print("INSIDE GET NAMES")
    if request.method == 'POST':
        designation = request.POST.get('d')
        result_set = []
        trimmed_role= str(designation).strip()
        all_users = CustomUser.objects.filter(role=trimmed_role, is_student=False)
        print('..',trimmed_role,'..')
        for user in all_users:
            print(user.first_name,' ', user.id)
            result_set.append({'first_name': user.first_name,'last_name': user.last_name, 'id': user.id})
        return HttpResponse(json.dumps(result_set), content_type='application/json')

    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_type="application/json"
        )

@csrf_exempt
@login_required_message(message="You should be logged in, in order to perform this")
@login_required(login_url="/login/")
def Activate_Users(request):
    users = CustomUser.objects.all()
    response = {}
    response['users'] = users
    return render(request, 'accounts/activate_users.html', response)

@csrf_exempt
@login_required_message(message="You should be logged in, in order to perform this")
@login_required(login_url="/login/")
def Activate(request, uid):
    user = CustomUser.objects.get(pk=uid)
    user.is_active = True
    user.save()
    response = {}
    users = CustomUser.objects.all()
    response['users'] = users
    print("activate")
    return render(request, 'accounts/activate_users.html', response)

@csrf_exempt
@login_required_message(message="You should be logged in, in order to perform this")
@login_required(login_url="/login/")
def Deactivate(request, uid):
    user = CustomUser.objects.get(pk=uid)
    user.is_active = False
    user.save()
    response = {}
    users = CustomUser.objects.all()
    response['users'] = users
    print("deactivate")
    return render(request, 'accounts/activate_users.html', response)

templates/accounts/activate_users.html
{% extends 'base.html' %}
{% load static %}
{% block content3 %}"../media/{{ user.image }}"{% endblock content3 %}
{% block content4 %}"../media/{{ user.image }}"{% endblock content4 %}
{% block content %}
    <body>
    {% if messages %}
        {% for mes in messages %}
            <div class="alert alert-success message_container">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>{{ mes }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    <div class="row main_header" style="text-align: center">
        <h2>All Users</h2>
    </div>

    <div class="container" >
        <div>
            <table class="table table-striped dt-responsive table-responsive-md" id="display_table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">S. No.</th>
                    <th scope="col">User ID</th>
                    <th scope="col">Name</th>
                    <th scope="col">Designation</th>
                    <th scope="col">Actions</th>

                </tr>
                </thead>
                <tbody>


                {% for i in users %}

                    {% if i.is_superuser == 0 %}
                        <tr>
                            <td style="vertical-align:middle">{{ forloop.counter }}</td>
                            <td style="vertical-align:middle; ">{{ i.id}}</td>
                            <td style="vertical-align:middle">{{ i.first_name }} {{ i.last_name }}</td>
                            {%  if i.is_student %}
                                <td style="vertical-align:middle">Student</td>
                            {% else %}
                                <td style="vertical-align:middle">{{ i.role }}</td>
                            {%  endif %}
                            {% if i.is_active %}
                                <td style="vertical-align:middle"><a class="btn btn-danger" href="{% url 'accounts:Deactivate' i.id %}">Dectivate</a></td>
                            {% else %}
                                <td style="vertical-align:middle"><a class="btn btn-success" href="{% url 'accounts:Activate' i.id %}">Activate</a></td>
                            {% endif %}
                        </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
        <script type="text/javascript">
            function approveButtonClicked (appid) {
                console.log("ID=",appid)
                document.getElementById("idChecker").value = appid;
                return true;
            }
        </script>
    </body>

{% endblock content %}

templates/accounts/login.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}
{% load static %}
{% block content %}
    <body onload="Check()">
    <div class="row main_header">
        <!-- <center><h2><b>Registration</b></h2></center>
         <br>-->
    </div>
    <script>
        $(document).ready(function () {
            // messages timeout for 10 sec
            setTimeout(function () {
                $('.message_container').fadeOut('slow');
            }, 3000);
        });
    </script>
    <div class="container">
        {% if messages %}
            {% for mes in messages %}
                <div class="alert alert-warning message_container">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>{{ mes }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        <div class="row" style="margin-top: 10%;">
            <div class="col-sm-6 col-sm-offset-3">

                <div id="uploadForm" class="well well-lg">
                    <legend>Login</legend>
                    <form method="POST" action="/login/">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="formText" for="firstName">Username</label>
                            <input for="firstName" class="form-control" name="username" id="fn" required>
                        </div>

                        <div class="form-group">
                            <label class="formText" for="password1">Password</label>
                            <input for="password1" class="form-control" id="password" name="password" type="password"
                                   required>
                        </div>

                        <center>
                            <button type="submit" id="btn"  class="formButton">Login</button>
                        </center>
                    </form>
                    <div class="border-top pt-3">
                        <small class="text-muted">
                            Need registered?<br>
                            <a class="ml-2" href="/student/register">Register as Student</a>
                            <br>Or<br>
                            <a class="ml-2" href="/staff/register">Register as Staff member</a>
                        </small>
                    </div>
                    <br>

                </div>
            </div>
        </div>
    </div>

    </body>

    {# Main Section #}
{% endblock content %}

templates/accounts/staff_register.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}
{% load static %}
{% block content3 %}"../../media/{{ user.image }}"{% endblock content3 %}
{% block content %}

    <body>
    <script>
        $(document).ready(function () {
            // messages timeout for 10 sec
            setTimeout(function () {
                $('.message_container').fadeOut('slow');
            }, 3000);
        });
    </script>
    <div class="container" style="min-width:min-content;margin-bottom: 8%">
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-warning message_container">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>{{ error }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        <div class="row" style="margin-top: 2%;">
            <div class="col-sm-6 col-sm-offset-3">
                <div id="uploadForm" class="well well-lg">
                    <formset>
                        {% if user.is_authenticated %}
                            <legend>Update Staff Profile</legend>
                        {% else %}
                            <legend>Register Staff</legend>
                        {% endif %}
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                {% for field in form %}
                                    <label class="formText">
                                        {{ field.label_tag }}
                                    </label> 
                                    {{ field }}
                                    <br>
                                {% endfor %}
                            </div>
                            {% if user.is_authenticated %}
                                <div class="form-group">
                                    <button class="formButton" type="submit">Update</button>
                                </div>
                            {% else %}
                                <div class="form-group">
                                    <button class="formButton" type="submit">Sign Up</button>
                                </div>
                                </form>
                                <div class="border-top pt-3">
                                    <small class="text-muted">
                                        Already Have An Account? <a class="ml-2" href="/login">Sign In</a>
                                    </small>
                                </div>
                            {% endif %}
                    </formset>
                    <br>
                </div>
            </div>
        </div>
    </div>
    </div>
    </body>
{% endblock content %}

templates/accounts/student_register.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}
{% load static %}
{% block content3 %}"../../media/{{ user.image }}"{% endblock content3 %}
{% block content %}
    <body>
    <script>
        $(document).ready(function () {
            // messages timeout for 10 sec
            setTimeout(function () {
                $('.message_container').fadeOut('slow');
            }, 3000);
        });
    </script>
    <div class="container" style="min-width:min-content;margin-bottom: 8%">
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-warning message_container">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>{{ error }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        <div class="row" style="margin-top: 2%;">
            <div class="col-sm-6 col-sm-offset-3">
                <div id="uploadForm" class="well well-lg">
                    <formset>
                        {% if user.is_authenticated %}
                            <legend>Update Student Profile</legend>
                        {% else %}
                            <legend>Register Student</legend>
                        {% endif %}
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                {% for field in form %}
                                    <label class="formText">
                                        {{ field.label_tag }}
                                    </label>
                                    {{ field }}
                                    <br>
                                {% endfor %}
                            </div>
                            {% if user.is_authenticated %}
                                <div class="form-group">
                                    <button class="formButton" type="submit">Update</button>
                                </div>
                            {% else %}
                                <div class="form-group">
                                    <button class="formButton" type="submit">Sign Up</button>
                                </div>
                                </form>
                                <div class="border-top pt-3">
                                    <small class="text-muted">
                                        Already Have An Account? <a class="ml-2" href="/login">Sign In</a>
                                    </small>
                                </div>
                            {% endif %}
                    </formset>
                    <br>
                </div>
            </div>
        </div>
    </div>
    </div>
    </body>
{% endblock content %}