content/urls.py
from django.urls import re_path
from django.conf.urls.static import static
from django.urls import include, path
from . import  views
from office_file_tracking_system import  settings

app_name='content'

urlpatterns = [
                re_path(r'^scholarships/$', views.Show_Scholarships, name=''),
                re_path(r'^scholarships/(?P<s_id>\w+)', views.Scholarship_Detail, name='Scholarship_Detail'),
                path('track_application/', views.Track_Application, name='Track_Application'),
                re_path('apply/', views.Apply, name='Apply'),
                path('add_scholarship', views.Add_Scholarship, name='Add_Scholarship'),
                path('pending_approvals/', views.Show_Pending_Approvals, name='Show_Pending_Approvals'),
                path('track_student_applications/', views.Track_Student_Applications, name='Track_Student_Applications'),
                path('approve/', views.Approve, name='Approve'),
                path('reject/', views.Reject, name='Reject'),
                path('about/', views.About, name='About'),
                path('profile/', views.Profile, name='Profile'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

office_file_tracking_system/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf.urls.static import static
from office_file_tracking_system import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include(('accounts.urls', 'accounts'), namespace='accounts')),
    re_path(r'content/', include(('content.urls', 'content'), namespace='content')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

content/models.py
from django.core.validators import FileExtensionValidator
from django.db import models
from django.db.models.base import Model
from accounts.models import CustomUser
from django.template.defaultfilters import slugify
from django.utils.text import slugify

def get_pdf_path(instance, filename):
    return 'Attached_files/{0}/pdf/{1}'.format(instance.app_id, filename)


class Application_Count(models.Model):
    app_cnt = models.IntegerField(default=0)

    def __unicode__(self):
        return str(self.app_cnt)


class Scholarship(models.Model):
    name = models.CharField(max_length=255, default='')
    # slug = models.SlugField(max_length=30, unique=True, editable=False)
    abbreviation = models.CharField(max_length=10, default='')
    department = models.ForeignKey('accounts.Department', verbose_name="Department", on_delete=models.CASCADE, blank=True,
                                   null=True)
    receiver_authority_id = models.IntegerField(default=1)
    requirements_info = models.TextField(default='Requirement information needs to be updated.')
    max_step = models.IntegerField(default="1")


    def __str__(self):
        return self.name


class Application(models.Model):
    app_id = models.CharField(max_length=20, primary_key=True)
    request = models.ForeignKey(Scholarship, verbose_name="Request", on_delete=models.CASCADE,default=1)
    applicant = models.ForeignKey(CustomUser, verbose_name="Applicant", on_delete=models.CASCADE,default=1)
    category = models.CharField(max_length=300, default="")
    title = models.CharField(max_length=300, default="")
    department = models.ForeignKey('accounts.Department', verbose_name="Department", on_delete=models.CASCADE, blank=True,
                                   null=True)

    attached_pdf = models.FileField(upload_to='documents/',null=True, blank=True, default=None)

    # attached_pdf = models.FileField(upload_to=get_pdf_path,validators=[FileExtensionValidator(["pdf"])],
    #                                null=True, blank=True, default=None)

    current_authority = models.IntegerField(max_length=300, default="")
    current_step = models.IntegerField(default="0")
    max_step = models.IntegerField(default="1")
    is_approved = models.BooleanField(default=False)
    is_rejected = models.BooleanField(default=False)
    
    def __unicode__(self):
        return str(self.app_id)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.category)
        super(Application, self).save(*args, **kwargs)

content/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from django.views.decorators.csrf import csrf_exempt
from content.decorators import login_required_message
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import datetime
from accounts.models import Department

@csrf_exempt
def checkuserifscrutinyuser(user):
    if user.groups.filter(name="owner").exists() and user.is_superuser:
        return True
    else:
        return False

@csrf_exempt
@login_required_message(message="You should be logged in, in order to perform this")
@login_required(login_url="/login/")
def Show_Scholarships(request):
    response = {}
    response['scholarships'] = Scholarship.objects.all()
    return render(request, 'content/all_scholarships.html', response)

@csrf_exempt
@login_required_message(message="You should be logged in, in order to perform this")
@login_required(login_url="/login/")
def Scholarship_Detail(request, s_id):
    response = {}
    app = Application.objects.filter(request=s_id, applicant=request.user.id)
    if len(app)>0:
        response['alreadyApplied'] = True
        response['app_id'] = app[0].app_id
        print("IF : ",response['app_id'])
    else:
        response['alreadyApplied'] = False
        response['app_id'] = None
        print("ELSE : ", response['app_id'])

    response['scholarship'] = Scholarship.objects.get(pk=s_id)
    return render(request, 'content/scholarship_detail.html', response)

@csrf_exempt
@login_required(login_url="/login/")
def Apply(request):
    s_id = request.POST.get('scholarship_id')
    sch = get_object_or_404(Scholarship, id = s_id)
    user_id = request.user.id
    user = get_object_or_404(CustomUser,id=user_id)
    app = Application.objects.filter(request=s_id, applicant=user_id)
    if len(app)>0:
        messages.info(request, "You have already applied to this scholarship")
        new_app = app[0]
    else:
        cnt = Application_Count.objects.get()
        year = datetime.datetime.now().year
        yy = str(year)
        p1 = yy[2:]
        p2 = str(cnt.app_cnt).zfill(4)
        Name = "APP"
        app_id = Name + p1 + p2
        cnt.app_cnt += 1
        cnt.save()
        print("App id : ",app_id)
        new_app = Application.objects.create(app_id=app_id, current_authority=sch.receiver_authority_id)
        new_app.department = user.department
        new_app.category = request.POST.get('application_type')
        new_app.applicant = user
        new_app.request = sch
        new_app.title = sch.name
        new_app.current_step = 0
        new_app.max_step = sch.max_step
        new_app.is_approved = False
        new_app.attached_pdf = request.FILES.get("up_files","documents/Resume.pdf")
        new_app.department_id = user.department
        new_app.save()
        messages.success(request, "You have successfully applied to this scholarship")

    data = {}
    data['alreadyApplied'] = True
    data['scholarship'] = sch
    response = {}
    response['scholarship'] = sch
    response['app_id'] = new_app.app_id
    return render(request, 'content/scholarship_detail.html', response)

@csrf_exempt
@login_required_message(message="You should be logged in, in order to perform this")
@login_required(login_url="/login/")
def Show_Pending_Approvals(request):
    applications = Application.objects.all()
    departments = Department.objects.all()
    response = {}
    response['applications'] = applications
    response['departments'] = departments
    designations = {'Teacher', 'Faculty Advisor', 'Dean', 'Head of Department', 'Director'}
    response['designations'] = designations
    return render(request, 'content/show_pending_approvals.html', response)

@csrf_exempt
@login_required_message(message="You should be logged in, in order to perform this")
@login_required(login_url="/login/")
def Approve(request):
    app_id = request.POST.get('id_checker')
    app = Application.objects.filter(app_id=app_id)
    app = app[0]
    print('Last Step=',app.current_step)
    app.current_step += 1
    next_id = request.POST.get('names')
    cur = CustomUser.objects.get(pk=app.current_authority)
    app.current_authority = next_id
    if app.current_step == app.max_step:
        print("Got approved")
        app.is_approved = True

    app.save()
    applications = Application.objects.all()
    departments = Department.objects.all()
    response = {}
    response['applications'] = applications
    response['departments'] = departments
    designations = {'Teacher', 'Faculty Advisor', 'Dean', 'Head of Department', 'Director'}
    response['designations'] = designations
    return render(request, 'content/show_pending_approvals.html', response)


@csrf_exempt
@login_required_message(message="You should be logged in, in order to perform this")
@login_required(login_url="/login/")
def Reject(request):
    app_id = request.POST.get('id_checker')
    reason = request.POST.get('reason')
    app_id = str(app_id).strip()
    print(app_id)
    app = Application.objects.get(pk=app_id)
    print('Rejected at Step=',(app.current_step+1), 'Reason: ',reason)
    app.is_rejected = True
    app.save()
    applications = Application.objects.all()
    departments = Department.objects.all()
    response = {}
    response['applications'] = applications
    response['departments'] = departments
    designations = {'Teacher', 'Faculty Advisor', 'Dean', 'Head of Department', 'Director'}
    response['designations'] = designations
    return render(request, 'content/show_pending_approvals.html', response)


@csrf_exempt
@login_required_message(message="You should be logged in, in order to perform this")
@login_required(login_url="/login/")
def Track_Application(request):
    if request.POST:
        app_id = request.POST.get('app_id')
        application = Application.objects.filter(app_id=app_id)
        for a in application:
            print(a.app_id)
        auth = CustomUser.objects.get(pk=application[0].current_authority)
        response = {
            'application': application[0],
            'auth' : auth
        }

    else:
        response = {
            'application': None,
            'auth': None
        }
    return render(request, 'application/track_application.html', response)

@csrf_exempt
@login_required_message(message="You should be logged in, in order to perform this")
@login_required(login_url="/login/")
def Track_Student_Applications(request):
    if request.POST:
        app_id = request.POST.get('app_id')
        application = Application.objects.filter(app_id=app_id)
        for a in application:
            print(a.app_id)
        response = {
            'application': application[0]
        }
    else:
        response = {
            'application': None
        }
    return render(request, 'application/track_application.html', response)

@csrf_exempt
@login_required_message(message="You should be logged in, in order to perform this")
@login_required(login_url="/login/")
def Add_Scholarship(request):
    user = CustomUser.objects.get(pk=request.user.id)
    if user.role == "Admin":
        if request.method == "POST":
            user = CustomUser.objects.get(pk=request.user.id)
            response = {}
            sch = Scholarship.objects.create(name = request.POST['title'], abbreviation= request.POST['abbreviation'])
            try:
                dept = Department.objects.get(name=request.POST['department'])
                sch.department = dept[0]
            except Exception as e:
                sch.department = None
                
            sch.receiver_authority_id = request.POST['receiver_authority_id']
            sch.requirements_info = request.POST['requirements_info']
            sch.max_step = request.POST['max_step']
            sch.save()
            messages.success(request, "Scholarship has been added successfully.")
        if request.user.is_admin:
            return render(request, 'content/add_scholarship.html')
        else:
            return render(request, 'student_home.html')

@csrf_exempt
def About(request):
    return render(request, 'content/about.html')

@csrf_exempt
@login_required_message(message="You should be logged in, in order to perform this")
@login_required(login_url="/login/")
def Profile(request):
    return render(request, 'content/profile.html')

templates/content/about.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}
{% block content3 %}"../media/{{ user.image }}"{% endblock content3 %}
{% block content4 %}"../media/{{ user.image }}"{% endblock content4 %}
{% load static %}
{% block content %}
    <head>
        <script src="https://kit.fontawesome.com/57456f662e.js" crossorigin="anonymous"></script>
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    </head>
    <body>
        <div class="about-section">
            <div class="inner-container">
              <h1> Abstract</h1>
              <p class="text">
                  Application Tracking System
                <br>
                <br>
                This project is developed to digitize the process of application and verification 
                for college documents and other purpose and to provide a hectic free solution for 
                the process of circulating new forms.In this system a new Staff member or a Student 
                can register themselves and then login to use the system.Students can apply for any 
                ongoing event and their Application automatically goes to the concerned authority 
                who can redirect it to higher authorities and then they can approve it or reject it 
                and the Applicants will be able to track their applications in real time.
              </p>
            </div>
          </div>
    </body>

{% endblock content %}

templates/content/add_scholarship.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}
{% load static %}
{% block content %}
    <head>
        <script defer src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    </head>
    <body onload="init()">
    <div class="row main_header">
        <!-- <center><h2><b>Registration</b></h2></center>
         <br>-->
    </div>

    <div class="container" style="min-width:min-content;margin-bottom: 8%">

        <div class=" md-3" style="margin-top:2%;">

            <div class=" sm-3 ">
                <h3 style="text-align:center">Add New Application Form</h3>
                    <div id="uploadForm" class="well well-lg">
                    <form method="POST" action="/content/add_scholarship" enctype="multipart/form-data"
                          onsubmit="return validateForm();">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="formText">Title *</label>
                            <input class="form-control" name="title" id="title" required>
                        </div>
                        <div class="form-group">
                            <label class="formText">Abbreviation *</label>
                            <input class="form-control" name="abbreviation" id="abbreviation" required>
                        </div>
                        <div class="form-group">
                            <label class="formText">Department </label>
                            <input class="form-control" name="department" id="department" >
                        </div>
                        <div class="form-group">
                            <label class="formText">Receiver ID </label>
                            <input class="form-control" name="receiver_authority_id" id="receiver_authority_id" >
                        </div>
                        <div class="form-group">
                            <label class="formText">Requirements Info </label>
                            <input class="form-control" name="requirements_info" id="requirements_info" >
                        </div>
                        <div class="form-group">
                            <label class="formText">Max Verification Level</label>
                            <input class="form-control" name="max_step" id="max_step" >
                        </div>
                        <center>
                            <button type="submit" id="btn"  class="formButton">Add</button>
                        </center>
                    </form>
                    <br>

                </div>
            </div>
        </div>
    </div>

    </body>

    {# Main Section #}
{% endblock content %}

templates/content/all_scholarships.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}
{% load static %}
{% block content3 %}"../media/{{ user.image }}"{% endblock content3 %}
{% block content4 %}"../media/{{ user.image }}"{% endblock content4 %}
{% block content %}
    <head>
        <script src="https://kit.fontawesome.com/57456f662e.js" crossorigin="anonymous"></script>
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    </head>
    <body>

        <div class="site-section">
            <div class="container">
                <div>
                    <table class="table table-striped dt-responsive table-responsive-md" id="display_table">
                        <thead class="thead-dark">
                        <tr>
                            <th scope="col">S. No.</th>
                            <th scope="col">Title</th>
                            <th scope="col">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for i in scholarships %}
                            <tr>
                                <td style="vertical-align:middle">{{ forloop.counter }}</td>
                                <td style="vertical-align:middle">{{ i.name }}</td>
                                {% if user.is_authenticated and user.is_superuser %}
                                    <td scope="col">
                                        <a href="/content/scholarship_detail/{{ i.id }}" class="btn btn-success">Details</a>
                                    </td>
                                {% else %}
                                    <td scope="col">
                                            <a style="font-weight: bold"
                                               href="/content/scholarships/{{ i.id }}"
                                               class="btn btn-info">
                                               Apply</a>
                                    </td>
                                {% endif %}

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </body>

{% endblock content %}

templates/content/scholarship_detail.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}
{% load static %}
{% block content3 %}"../media/{{ user.image }}"{% endblock content3 %}
{% block content4 %}"../media/{{ user.image }}"{% endblock content4 %}
{% block content %}
    <body>
    {% if messages %}
        {% for mes in messages %}
            <div class="alert alert-success message_container">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>{{ mes }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    <div class="row main_header" style="text-align: center">
        <h2>{{ scholarship.name }}</h2>
        <div class="container" style="margin-bottom: 50px">
            <div class="col-sm-6 col-sm-offset-3" >
                {% if alreadyApplied %}
                    <div id="uploadForm" class="well well-lg" style="text-align: center; font-size:20px;">
                        You have already applied here.
                        <div style="color:rgb(255, 0, 0)">Your Application ID  is : <b>{{ app_id }}</b></div>
                    </div>
                {% else %}
                <div id="uploadForm" class="well well-lg">
                    <legend>Application for {{ scholarship.name }}</legend>
                    <form method="POST" action="/content/apply/">
                        {% csrf_token %}
                        <input type="hidden" name="application_type" id="type_checker" value="scholarship">
                        <input type="hidden" name="scholarship_id" id="id_checker" value="{{scholarship.id}}">

                        <div class="form-group">
                            <label class="formText" for="password1">Upload Documents</label>
                            <input class="form-control" type="file" id="up_files" name="up_files" required>
                            {% csrf_token %}
                        </div>

                        <center>
                            <button type="submit" id="btn"  class="formButton">Apply</button>
                        </center>
                    </form>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</body>

{% endblock content %}

templates/content/show_pending_approvals.html
{% extends 'base.html' %}
{% load static %}
{% block content3 %}"../media/{{ user.image }}"{% endblock content3 %}
{% block content4 %}"../media/{{ user.image }}"{% endblock content4 %}
{% block content %}
    <head>
        <script>
            $(document).ready(function () {
                $('select#selectDesignation').change(function () {
                    let optionSelected = $(this).find("option:selected");
                    {#let valueSelected  = optionSelected.val();#}
                    let designation_title = optionSelected.text();
                    console.log("Designation selected is :", designation_title);
                    $.ajax({
                        url: "/accounts/getNames/",
                        type: "POST",
                        data: {'d': designation_title},
                        success: function (names) {
                            $("#selectNames option").remove();
                            $("#selectNames").append("<option selected disabled>Choose Name</option>");
                            for (var i = names.length - 1; i >= 0; i--) {
                                {
                                    console.log(names[i].id + "   ");
                                }
                                $("#selectNames").append("<option value=" + names[i].id + ">" + names[i].first_name+" "+
                                    names[i].last_name+ "</option>");
                            }
                        }
                    });
                });
            });
        </script>
    </head>
    <body>
    {% if messages %}
        {% for mes in messages %}
            <div class="alert alert-success message_container">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>{{ mes }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    <div class="row main_header" style="text-align: center">
        <h2>All Pending Approvals</h2>
    </div>

    <div class="container" >
        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">

              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">Choose the next Authority to approve.</h4>
                </div>
                <div class="modal-body">
                 <form method="POST" action="{%  url 'content:Approve' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="hidden" name="id_checker" id="idChecker" value="0">
                        <label class="formText">Select Department</label>
                        <select class="form-control" id="selectDepartment" name="departments" required>
                            <option selected disabled>Choose department</option>
                            {% for department in departments %}
                                <option value="{{ department.id }}">
                                    {{ department.name }}, ({{ department.abbreviation }})
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="formText">Select Designation</label>
                        <select class="form-control" id="selectDesignation" name="roles" required>
                            <option selected disabled>Choose designation</option>
                            {% for designation in designations %}
                                <option value="{{ designation }}">
                                    {{ designation }}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="formText">Select Name</label>
                        <select class="form-control" id="selectNames" name="names" required>
                            <option selected disabled>Choose name</option>
                        </select>
                    </div>
                    <center>
                        <button type="submit" id="btn" class="formButton" style="height:40px; width: 120px; padding:0px 10px">Approve and redirect</button>
                    </center>

                 </form>


                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              </div>

            </div>
          </div>

    <div class="modal fade" id="myModal2" role="dialog">
            <div class="modal-dialog">

              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">Please specify the reason to reject.</h4>
                </div>
                <div class="modal-body">
                 <form method="POST" action="{%  url 'content:Reject' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                     <div class="form-group">
                         <input type="hidden" name="id_checker" id="idChecker2" value="0">
                        <label class="formText">Reason</label>
                        <textarea class="form-control" id="reason_textbox" name="reason" required>
                        </textarea>
                    </div>
                    <center>
                        <button type="submit" id="btn" class="formButton" style="height:40px; width: 120px; padding:0px 10px">Reject</button>
                    </center>

                 </form>


                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              </div>

            </div>
          </div>
        <div>
            <table class="table table-striped dt-responsive table-responsive-md" id="display_table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">S. No.</th>
                    <th scope="col">Application ID</th>
                    <th scope="col">Applicant Name</th>
                    <th scope="col">Title</th>
                    <th scope="col">Status</th>
                    <th scope="col">Attached Documents</th>
                    <th scope="col">Actions</th>

                </tr>
                </thead>
                <tbody>

                {% for i in applications %}

                    <tr>
                        <td style="vertical-align:middle">{{ forloop.counter }}</td>
                        <td style="vertical-align:middle; ">{{ i.app_id}}</td>
                        <td style="vertical-align:middle">{{ i.applicant.first_name }} {{ i.applicant.last_name }}</td>
                        <td style="vertical-align:middle">{{ i.title }}</td>
                        {% if i.is_approved %}
                            <td style="vertical-align:middle;color:green">Approved</td>
                        {% elif i.is_rejected %}
                            <td style="vertical-align:middle;color:red">Rejected</td>
                        {% else %}
                            <td style="vertical-align:middle;color:blue">Awaiting {{ i.current_authority.first_name }}'s Approval<br>
                                            (Step {{ i.current_step }} of {{ i.max_step }})
                            </td>
                        {% endif %}
                        <td style="vertical-align:middle"><a href="../../media/{{ i.attached_pdf }}">View</a></td>
                        {% if user.is_authenticated and user.id == i.current_authority and not i.is_approved and not i.is_rejected%}
                            <td scope="col">
                                <a id="{{ i.app_id }}" class="btn btn-success"data-toggle="modal" data-target="#myModal"
                                       onclick="return approveButtonClicked(this.id)">Approve</a>
                                <a id="{{ i.app_id }}1" class="btn btn-danger"data-toggle="modal" data-target="#myModal2"
                                       onclick="return rejectButtonClicked(this.id)">Reject</a>
                            </td>
                        {% else %}
                            <td style="vertical-align:middle;color:red">N/A</td>
                        {% endif %}

                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
        <script type="text/javascript">
            function approveButtonClicked (appid) {
                console.log("ID=",appid)
                document.getElementById("idChecker").value = appid;
                return true;
            }
            function rejectButtonClicked (appid) {
                console.log("before ID=",appid)
                appid = appid.slice(0, -1)
                console.log("after ID=",appid)
                document.getElementById("idChecker2").value = appid;
                return true;
            }
        </script>
    </body>

{% endblock content %}