content/urls.py
from django.urls import re_path
from django.conf.urls.static import static
from django.urls import include, path
from . import  views
from office_file_tracking_system import  settings

app_name='content'

urlpatterns = [
                re_path(r'^scholarships/$', views.Show_Scholarships, name=''),
                re_path(r'^scholarships/(?P<s_id>\w+)', views.Scholarship_Detail, name='Scholarship_Detail'),
                path('track_application/', views.Track_Application, name='Track_Application'),
                re_path('apply/', views.Apply, name='Apply'),
                path('add_scholarship', views.Add_Scholarship, name='Add_Scholarship'),
                path('pending_approvals/', views.Show_Pending_Approvals, name='Show_Pending_Approvals'),
                path('track_student_applications/', views.Track_Student_Applications, name='Track_Student_Applications'),
                path('approve/', views.Approve, name='Approve'),
                path('reject/', views.Reject, name='Reject'),
                path('about/', views.About, name='About'),
                path('profile/', views.Profile, name='Profile'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

office_file_tracking_system/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf.urls.static import static
from office_file_tracking_system import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include(('accounts.urls', 'accounts'), namespace='accounts')),
    re_path(r'content/', include(('content.urls', 'content'), namespace='content')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/application/application_details.html
{% extends 'base.html' %}
{% block title %}Home NIT ADDA{% endblock title %}
{% load static %}
{% block content3 %}"../media/{{ user.image }}"{% endblock content3 %}
{% block content4 %}"../media/{{ user.image }}"{% endblock content4 %}
{% block content %}
    <head>
        <script src="https://kit.fontawesome.com/57456f662e.js" crossorigin="anonymous"></script>
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    </head>
    <body>
        STUDENT | APPLICATION DETAILS
    </body>

{% endblock content %}

templates/application/application_form.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}
{% load static %}
{% block content3 %}"../media/{{ user.image }}"{% endblock content3 %}
{% block content4 %}"../media/{{ user.image }}"{% endblock content4 %}
{% block content %}
    <body onload="Check()">
    <div class="row main_header">
        <!-- <center><h2><b>Registration</b></h2></center>
         <br>-->
    </div>
    <script>
        $(document).ready(function () {
            // messages timeout for 10 sec
            setTimeout(function () {
                $('.message_container').fadeOut('slow');
            }, 3000);
        });
    </script>
    <div class="container">
        {% if messages %}
            {% for mes in messages %}
                <div class="alert alert-warning message_container">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>{{ mes }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        <div class="row" style="margin-top: 10%;">
            <div class="col-sm-6 col-sm-offset-3">

                <div id="uploadForm" class="well well-lg">
                    <legend>Application for {{ scholarship.name }}</legend>
                    <form method="POST" action="/apply/{{scholarship.id}}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="formText" for="firstName"></label>
                            <input for="firstName" class="form-control" name="username" id="fn" required>
                        </div>

                        <div class="form-group">
                            <label class="formText" for="password1">Password</label>
                            <input for="password1" class="form-control" id="password" name="password" type="password"
                                   required>
                        </div>

                        <center>
                            <button type="submit" id="btn"  class="formButton">Login</button>
                        </center>
                    </form>
                    <div class="border-top pt-3">
                        <small class="text-muted">
                            Need An Account? <a class="ml-2" href="/register">Sign Up Now</a>
                        </small>
                    </div>
                    <br>

                </div>
            </div>
        </div>
    </div>

    </body>

    {# Main Section #}
{% endblock content %}

templates/application/track_application.html
{% extends 'base.html' %}
{% load static %}
{% block content3 %}"../media/{{ user.image }}"{% endblock content3 %}
{% block content4 %}"../media/{{ user.image }}"{% endblock content4 %}
{% block content %}
    <head>
        <script>
            $(document).ready(function () {
                $('select#selectDesignation').change(function () {
                    let optionSelected = $(this).find("option:selected");
                    {#let valueSelected  = optionSelected.val();#}
                    let designation_title = optionSelected.text();
                    console.log("Designation selected is :", designation_title);
                    $.ajax({
                        url: "/accounts/getNames/",
                        type: "POST",
                        data: {'d': designation_title},
                        success: function (names) {
                            $("#selectNames option").remove();
                            $("#selectNames").append("<option selected disabled>Choose Name</option>");
                            for (var i = names.length - 1; i >= 0; i--) {
                                {
                                    console.log(names[i].id + "   ");
                                }
                                $("#selectNames").append("<option value=" + names[i].id + ">" + names[i].first_name+" "+
                                    names[i].last_name+ "</option>");
                            }
                        }
                    });
                });
            });
        </script>
    </head>
    <body>
    {% if messages %}
        {% for mes in messages %}
            <div class="alert alert-success message_container">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>{{ mes }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    <div class="row main_header" style="text-align: center">
        <h2>Track application by Reference ID</h2>
        <form method="POST" action="{%  url 'content:Track_Application' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group" style="width: 40%; margin: 25px auto">
{#                <input type="hidden" name="id_checker" id="idChecker" value="0">#}
                <label class="formText">Enter application id</label>
                <input typ="text" name="app_id" required>
            </div>
            <center>
                <button type="submit" id="btn"  class="formButton">Search</button>
            </center>
        </form>
    </div>

    {% if application %}
        <div class="container" >
        <div>
            <table class="table table-striped dt-responsive table-responsive-md" id="display_table">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Application ID</th>
                    <th scope="col">Applicant Name</th>
                    <th scope="col">Title</th>
                    <th scope="col">Status</th>
                    <th scope="col">Attached Documents</th>
                    {% if not user.is_student %}
                        <th scope="col">Actions</th>
                    {% endif %}
                </tr>
                </thead>
                <tbody>

                <tr>
                    <td style="vertical-align:middle">{{ application.app_id }}</td>
                    <td style="vertical-align:middle">{{ application.applicant.first_name }} {{ application.applicant.last_name }}</td>
                    <td style="vertical-align:middle">{{ application.title }}</td>
                    {% if application.is_approved %}
                        <td style="vertical-align:middle;color:green">Approved</td>
                    {% elif application.is_rejected %}
                        <td style="vertical-align:middle;color:rgb(255, 0, 0)">Application Rejected <br>at (Step {{application.current_step}} of {{application.max_step}}) by {{auth.role}}</td>
                    {% else %}
                        <td style="vertical-align:middle;color:blue">Awaiting {{auth.role}}'s approval <br>(Step {{application.current_step}} of {{application.max_step}})</td>
                    {% endif %}
                    <td style="vertical-align:middle"><a href="../../media/{{ application.attached_pdf }}">View</a></td>

                    {% if not user.is_student %}
                        {% if user.is_authenticated and user.id == application.current_authority %}
                            {% if application.is_approved  %}
                                <td style="vertical-align:middle;color:red">N/A</td>
                            {% else %}
                            <td scope="col">
                                <a id="{{ i.app_id }}" class="btn btn-success"data-toggle="modal" data-target="#myModal"
                                       onclick="return approveButtonClicked(this.id)">Approve</a>
                                <a id="{{ i.app_id }}1" class="btn btn-danger"data-toggle="modal" data-target="#myModal"
                                           onclick="return rejectButtonClicked(this.id)">Reject</a>
                            </td>
                            {% endif %}
                        {% else %}
                            <td style="vertical-align:middle;color:red">N/A</td>
                        {% endif %}
                    {% endif %}
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    {% endif %}

{% endblock content %}